pyvocz/templates/base.html

Fixed responsivity headers.

---

pyvocz/templates/cities/praha.html

only @kvbik merge Kubiku please ask @aleszoulek and @whiskybar if they are ok with this contact.

Add Prague orginizers :love_letter: - @kvbik merge

---

pyvocz/templates/cities/ostrava.html

Added contact info for Pyvo in Ostrava

---

pyvocz/static/style.css
pyvocz/templates/_base.html
pyvocz/views.py
test_pyvocz/test_generic.py

Added
- `https://pyvo.cz/zpetnovazebnik` and `https://pyvo.cz/feedback` redirects
- notice on every page that people should fill the form

Zpětnovazebník

---

pyvocz/filters.py
pyvocz/templates/event.html
pyvocz/views.py

Add external links to the Event page

---

pyvocz/views.py

@honzajavorek si stěžoval, že v kalendáři nemá Pyva, co ještě nikdo nenaplánoval...

Add some future events to the ICS exports

---

pyvocz/__main__.py

Jednodussi alternativa k pull requestu #55 na spraveni autoreloadu Jinja templatu v debug modu.

Fix Jinja templates auto reload in debug mode (simpler patch)

---

pyvocz/templates/event.html
pyvocz/views.py

Add a link to edit event yaml file on GitHub

---

pyvocz/static/style.css
pyvocz/templates/index.html
pyvocz/views.py

Preparations for Pyvo Olomouc on pyvo.cz
I need help with preparing better SVG images. The current version of SVG images is made from PNG (included) and has a transparent background.
Cc @encukou @fivaldi @mcurlej

New Pyvo in Olomouc

---

pyvocz/templates/index.html

Two or more, use a for!
(Olomouc was not listed)
I've replaced commas with full stops, because I was lazy to treat the last case specially.

List cities dynamically

---

pyvocz/templates/_base.html

Not sure if SVG will work, but we can change the image later. Ideally, we'd have some nice set of photos we can randomly pick from.

Add social media preview

---

pyvocz/app.py
pyvocz/static/style.css
pyvocz/templates/_base.html
pyvocz/templates/index.html
pyvocz/views.py

This should display correctly even if the events are too high.
Also add a cache-busting tag to the CSS.

Use flexbox to display events on the main page

---

pyvocz/templates/series.html

Fixes: https://github.com/pyvec/pyvo.cz/issues/80

templates/series: Hide history if there's just one event

---

pyvocz/static/coatofarms/brno-gray.svg
pyvocz/static/coatofarms/brno.svg
pyvocz/templates/index.html

Use approved by the Brno City Council (Rada města Brna) 13.2.2018. Meeting R7/157. Should be available at [1] soon.
Used SVGs from before, except I've changed the red colour according to the PDF they've e-mailed me. Their vector is ugly (non smooth curves).
See https://github.com/pyvec/pyvo.cz/issues/70#issuecomment-366980084
[1]: https://www.brno.cz/sprava-mesta/dokumenty-mesta/zapisy-z-rady-mesta-brna/

Reintroduce Brno CoA

---

pyvocz/templates/_base.html

It seems like the old code just expired. Had to generate a new one :(

Fix google verification code

---

pyvocz/templates/index.html

j.č.: **to** Pyvo --- mn.č.: **ta** Pyva --- pořádán**a**, konán**a**, ...
j.č. **to** setkání --- mn.č.: **ta** setkání --- pořádán**a**, konán**a**, ...
Nebo možná úplně jednoduše: "se konají" :-)

Czech grammar fix

---

pyvocz/static/coatofarms/hradec-kralove-gray.svg
pyvocz/static/coatofarms/hradec-kralove.svg
pyvocz/static/style.css
pyvocz/views.py

Tou ikonkou si nejsem moc jistý, ale tak zatím aspoň tohle :)
:exclamation: Mergnout nejspíš až po https://github.com/pyvec/pyvo-data/pull/133
Screenshot: ![image](https://user-images.githubusercontent.com/115487/43488894-759c0012-951b-11e8-8fe3-6bc5c65f6911.png)

Pyvo Hradec Králové

---

pyvocz/static/style.css
pyvocz/templates/_base.html

This revers "removed zpetnovazebnik" and builds on top of it.
This reverts commit e455f5fe4e85afd3f9d3e43dd955a753272e3622.

Add a note about the community sprint

---

pyvocz/templates/_base.html

Partially reverts commit 973b8b004b78045f63929bfbb7b417343c2558d7.

Comment out note about the community sprint

---

pyvocz/views.py

Fixes: https://github.com/pyvec/pyvo.cz/issues/106

iCal export: Add 'tentative-date' category

---

pyvocz/templates/index.html

Viz https://github.com/pyvec/pyvo.cz/issues/43#issuecomment-451652124

Fix English word in Czech text

---

pyvocz/views.py

I believe this was causing test failures for pyvo.cz for some time. Let's see if it passes.

Fix event query for the Series page

---

pyvocz/templates/index.html

Just a tiny change to correct one mistake and improve the English version.

Proofread description of Pyvo

---

pyvocz/templates/index.html
pyvocz/views.py
setup.py

Remove FEATURED_SERIES; instead de-emphasize events which last took place 6+ months ago

---

pyvocz/templates/index.html

Fixes https://github.com/pyvec/pyvo.cz/issues/120

Add some missing English translations

---

pyvocz/templates/_base.html

Temporary addition of COVID-19 restriction note.

Brno notice for COVID-19 restrictions

---

pyvocz/templates/_base.html

Since the meetups are resuming normal operation, an update to the
banner on the page is warranted.

Update the banner on the site with new wording.

---

pyvocz/templates/index.html

Fixes: https://github.com/pyvec/pyvo.cz/issues/133

Add py.amsterdam to friends

---

pyvocz/views.py

Fixes: https://github.com/pyvec/pyvo.cz/issues/129

Redirect /nepyvo (and all paths under it) to the Facebook group

---

pyvocz/__main__.py

Otherwise the app fails to start

pyvo-data needs to be loaded before the app is created

---

pyvocz/templates/_base.html

See https://pyvec.slack.com/archives/C12MP1GDB/p1635765591005700

Replace GA with SA
